# Generated by Django 3.1.6 on 2022-04-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('total_yoga_time', models.IntegerField()),
                ('sessions_joined', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
