# Generated by Django 3.1.6 on 2022-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0002_auto_20220416_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='skill_level',
            field=models.CharField(default='beginner', max_length=50),
        ),
    ]
