# Generated by Django 3.1.6 on 2022-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0003_userdetails_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='skill_level',
            field=models.CharField(max_length=50),
        ),
    ]
