# Generated by Django 3.1.6 on 2022-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0004_auto_20220417_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='classes_created',
            field=models.IntegerField(default=0),
        ),
    ]
