# Generated by Django 3.1.6 on 2022-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0005_userdetails_classes_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=50)),
                ('user', models.CharField(max_length=5000, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
