# Generated by Django 3.1.6 on 2022-04-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0006_yogaclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='image',
        ),
    ]
