# Generated by Django 3.1.6 on 2022-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0007_remove_yogaclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='tag',
            field=models.CharField(default='basics', max_length=10),
            preserve_default=False,
        ),
    ]
