# Generated by Django 3.1.6 on 2022-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0009_auto_20220417_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='user',
            field=models.CharField(max_length=5000),
        ),
    ]
