# Generated by Django 4.0.3 on 2022-04-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0011_auto_20220417_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='link',
            field=models.CharField(default='http://meet.google.com/new', max_length=50000),
        ),
    ]
