# Generated by Django 4.0.3 on 2022-04-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0012_alter_yogaclass_link'),
        ('yoga_main', '0012_auto_20220417_1533'),
    ]

    operations = [
    ]
