# Generated by Django 3.1.6 on 2022-04-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0012_alter_yogaclass_link'),
        ('yoga_main', '0012_auto_20220417_1533'),
    ]

    operations = [
    ]
