# Generated by Django 3.1.6 on 2022-04-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0013_merge_20220417_1920'),
        ('yoga_main', '0013_merge_20220418_0148'),
    ]

    operations = [
    ]
