# Generated by Django 3.1.6 on 2022-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0014_merge_20220417_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='date',
            field=models.DateField(),
        ),
    ]
