# Generated by Django 3.1.6 on 2022-04-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0015_auto_20220417_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='date',
            field=models.CharField(max_length=5000),
        ),
    ]
