# Generated by Django 4.0.4 on 2022-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0016_auto_20220417_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='password',
            field=models.CharField(default='test', max_length=559999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='link',
            field=models.CharField(max_length=50000),
        ),
    ]
