# Generated by Django 4.0.4 on 2022-04-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0013_merge_20220417_2326'),
        ('yoga_main', '0017_yogaclass_password_alter_yogaclass_link'),
    ]

    operations = [
    ]
