# Generated by Django 4.0.4 on 2022-04-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_main', '0018_merge_20220418_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='time',
            field=models.CharField(default='dpfkdoi', max_length=5000),
            preserve_default=False,
        ),
    ]
